name: Backend

on:
  push:
    branches:
      - main
    paths:
      - "cmd/**"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/backend.yaml"
  pull_request:
    paths:
      - "cmd/**"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/backend.yaml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.23.0"
      - run: go build ./...
      - run: go test ./...
